version: '3'

services:
  cassandra:
    image: cassandra:3.11.4
    restart: always
    ports:
      - 127.0.0.1:7199:7199
      - 127.0.0.1:9042:9042
    # postgres:
    #     image: postgres
    #     restart: always
    #     ports:
    #         - 127.0.0.1:5432:5432
    #     environment:
    #         - POSTGRES_USER=woyski
    #     volumes:
    #         - ./postgres_init:/docker-entrypoint-initdb.d
    # redis:
    #     image: redis
    #     restart: always
    #     ports:
    #         - 127.0.0.1:6379:6379

