---
swagger: '2.0'
info:
  title: Payments api
  version: '0'
schemes:
- http
consumes:
- application/json
produces:
- application/json
basePath: "/api/v0"
paths:
  "/payments":
    get:
      operationId: GetPayments
      produces:
      - application/json
      parameters:
      - name: offset
        in: query
        type: integer
        format: int64
        default: 0
      - name: length
        in: query
        type: integer
        format: int64
        default: 10
      responses:
        '200':
          description: Lists of payments
          schema:
            type: array
            items: 
              "$ref": "#/definitions/Payment"
        default:
          description: Error condition
          schema:
            "$ref": "#/definitions/error"
definitions:
  Payment:
    type: object
    properties:
      type:
        type: string
        example: Payment
      id:
        type: string
        format: uuid
        example: 4ee3a8d8-ca7b-4290-a52c-dd5b6165ec43
      organisation_id:
        type: string
        format: uuid
        example: 743d5b63-8e6f-432e-a8fa-c5d8d2ee5fcb
      version:
        type: integer
        format: int64
        example: 0
      attributes:
        "$ref": "#/definitions/Attributes"
    required:
    - type
    - id
    - organisation_id
    - version
    - attributes
  error:
    type: object
    properties:
      message:
        type: string
  Attributes:
    type: object
    properties:
      amount:
        type: string
        example: "100.21"
      beneficiary_party:
        "$ref": "#/definitions/PartyDescription"
      charges_information:
        "$ref": "#/definitions/ChargesInformation"
      currency:
        type: string
        example: GBP
      debtor_party:
        "$ref": "#/definitions/PartyDescription"
      end_to_end_reference:
        type: string
        example: Wil piano Jan
      # fx:
      numeric_reference:
        type: string
        example: "1002001"
      payment_id:
        type: string
        example: "123456789012345678"
      payment_purpose:
        type: string
        example: Paying for goods/services
      payment_scheme: 
        type: string
        example: FPS
      payment_type:
        type: string
        example: Credit
      processing_date:
        type: string
        format: date
        example: "2017-01-18"
      reference:
        type: string
        example: Payment for Em's piano lessons
      scheme_payment_sub_type:
        type: string
        example: InternetBanking
      scheme_payment_type:
        type: string
        example: ImmediatePayment
      sponsor_party:
        "$ref": "#/definitions/PartyDescription"
  PartyDescription:
    type: object
    required:
      - account_number
      - bank_id
      - bank_id_code
    properties:
      account_name:
        type: string
        example: W Owens
      account_number:
        type: string
        example: "31926819"
      account_number_code:
        type: string
        example: BBAN
      account_type:
        type: integer
        format: int32
        example: 0
      address:
        type: string
        example: 1 The Beneficiary Localtown SE2
      bank_id:
        type: string
        example: "403000"
      bank_id_code:
        type: string
        example: GBDSC
      name:
        type: string
        example: Wilfred Jeremiah Owens
  ChargesInformation:
    type: object
    properties:
      bearer_code:
        type: string
        example: SHAR
      sender_charges:
        type: array
        items:
          "$ref": "#/definitions/SenderCharge"
      receiver_charges_amount:
        type: string
        example: "5.00"
      receiver_charges_currency:
        type: string
        example: USD
  SenderCharge:
    type: object
    properties:
      amount:
        type: string
        example: "5.00"
      currency:
        type: string
        example: "USD"

